### ISSUE TITLE
sig sg552 commando isg, wpn_sig552_isg_siber, all scopes dont render decal/lighting etc

### ISSUE THREAD

**Issue by Hoshizoku** [Redotix/GAMMA-3D-Shader-Based-Scopes#10]
im not sure if its even in lootlist, but apparently (03) BAS-2022 RIFLES - ANDTHEHEROIS adds it
no rendering of the new shader i guess 

packs involved: 
[weapons] BaS22 Rifles
3DSS for BaS22

https://discord.com/channels/912320241713958912/1219433143069708299/1257632074589016116

![grafik](https://github.com/Redotix/GAMMA-3D-Shader-Based-Scopes/assets/174358400/e426b805-ce50-415c-9174-798d055b4f00)

**Comment by andtheherois** [comment]
fixed in next update
