### ISSUE TITLE
wpn_winchester1873, side mount scope ('side'), blue iron sight

### ISSUE THREAD

**Issue by Hoshizoku** [Redotix/GAMMA-3D-Shader-Based-Scopes#11]
blue iron sight with and without side scope on the Winchester1873

involved packs
im not sure tbh, guess 3DSS.for.GAMMA-1.3

https://discord.com/channels/912320241713958912/1219433143069708299/1257636717436080169

![grafik](https://github.com/Redotix/GAMMA-3D-Shader-Based-Scopes/assets/174358400/03467b3a-6bbe-48ae-a95f-a94ba2a4a404)

**Comment by andtheherois** [comment]
added missing textures.
