### ISSUE TITLE
SVD (wpn_svd_m1), all scopes tritium sights bleed through

### ISSUE THREAD

**Issue by Hoshizoku** [Redotix/GAMMA-3D-Shader-Based-Scopes#12]
SVD (wpn_svd_m1), all scopes tirtium sights bleed through (same as phantoms aks)

involved packs:
3DSS.for.GAMMA-1.31

https://discord.com/channels/912320241713958912/1219433143069708299/1257891022726234123

![grafik](https://github.com/Redotix/GAMMA-3D-Shader-Based-Scopes/assets/174358400/d3185c64-9a1e-4296-a78b-c03161ac231b)

**Comment by andtheherois** [comment]
FIXED IN THE NEXT PATCH
