### ISSUE TITLE
SCAR-H "Specialist" Magnified Scope Visual Bug

### ISSUE THREAD

**Issue by th9doom** [Redotix/GAMMA-3D-Shader-Based-Scopes#16]
Magnified scope is bugged for me, no mods for SCAR-H are installed, load order is correct, no "regular" mods below 3DSS mods. 

![image](https://github.com/Redotix/GAMMA-3D-Shader-Based-Scopes/assets/175056205/004e91b6-6932-4d1c-bf2f-f1a474fd42b9)
![AnomalyDX11AVX_2024-07-08_22-11-23](https://github.com/Redotix/GAMMA-3D-Shader-Based-Scopes/assets/175056205/716554ce-5cc0-4759-a082-83377f80b091)

**Comment by andtheherois** [comment]
will be fixed in the re enabled module.
