### ISSUE TITLE
wpn_remington700 Crystal Shadow

### ISSUE THREAD

**Issue by Hoshizoku** [Redotix/GAMMA-3D-Shader-Based-Scopes#17]
probably better to just see

packs involved:
3dss for Gamma

https://discord.com/channels/912320241713958912/1219433143069708299/1260180797122678825

![grafik](https://github.com/Redotix/GAMMA-3D-Shader-Based-Scopes/assets/174358400/20a2924d-9a25-4923-9a1e-beab5bd91829)

**Comment by andtheherois** [comment]
fixed
