### ISSUE TITLE
wpn_sig550_luckygun, cant switch to canted sight without scope attached

### ISSUE THREAD

**Issue by Hoshizoku** [Redotix/GAMMA-3D-Shader-Based-Scopes#18]
wpn_sig550_luckygun, 
cant switch to the canted sight without a scope on, 
1x sights like c-more and eotech cant switch too

Packs involved:
3dss for Gamma

Sry, cant really screenshot anything usefull :)

**Comment by andtheherois** [comment]
Red dots shouldn't have a canted sight tos witch to because it's redundant. The base hud should be able to switch. I'll look into it for next update
