### ISSUE TITLE
akm_isg, rd74u tactical, rd74u  iron sight glow 

### ISSUE THREAD

**Issue by Redotix** [Redotix/GAMMA-3D-Shader-Based-Scopes#2]
![image](https://github.com/Redotix/GAMMA-3D-Shader-Based-Scopes/assets/118221809/e51808dc-5ef1-410c-abb1-d6d427d8a832)

**Comment by andtheherois** [comment]
these are phantom's AKs. They'll be fixed in that module later

**Comment by andtheherois** [comment]
fixed
