### ISSUE TITLE
wpn_ak103, ps01 Alt sight view "borked"

### ISSUE THREAD

**Issue by Hoshizoku** [Redotix/GAMMA-3D-Shader-Based-Scopes#20]
wpn_ak103, ps01 cant really see thru the iron sights lol (ignore if thats you trollin ;d)

involved packs: 
      3dss for base gamma

![grafik](https://github.com/andtheherois/3DSS-for-Gunslinger-AA12-AK101-AK103-BP-Gauss-Rifle/assets/174358400/78d02e3b-2f5c-462d-9779-0710b979b4f1)

**Comment by andtheherois** [comment]
turned off alt aim for this scope
