### ISSUE TITLE
Bad positioning - ACR (wpn_acr_tac)

### ISSUE THREAD

**Issue by lettuce338** [Redotix/GAMMA-3D-Shader-Based-Scopes#21]
Bad position of the ACR when using ACOG 3.5 scopes, both the standalone ACOG as well as the ACOG/RMR kit. Other scopes seem fine but haven't tested ALL of them yet. 

![image](https://github.com/Redotix/GAMMA-3D-Shader-Based-Scopes/assets/175345157/382ad87a-e6db-4fe4-8c5b-9a11e3c8f9e1)
![image](https://github.com/Redotix/GAMMA-3D-Shader-Based-Scopes/assets/175345157/68392dda-0470-4a4b-b17e-706b9ba7d060)

**Comment by andtheherois** [comment]
you most likely have an outdated version of juan's guns. i dont have this issue.
