### ISSUE TITLE
AUG A1 (wpn_aug) scope "prism" effect

### ISSUE THREAD

**Issue by lettuce338** [Redotix/GAMMA-3D-Shader-Based-Scopes#22]
Prism effect similar to that one issue shared in the discord thread 

![image](https://github.com/Redotix/GAMMA-3D-Shader-Based-Scopes/assets/175345157/bf227364-e71d-43da-8e57-b2e08493ba9a)

**Comment by andtheherois** [comment]
fixed in main scopes for next update
