### ISSUE TITLE
Elcan Specter black when zooming

### ISSUE THREAD

**Issue by napo1emon** [Redotix/GAMMA-3D-Shader-Based-Scopes#25]
Specter optic has a black area moving from side to side when zooming in and out. Screenshots attached.

![AnomalyDX11AVX 2024-10-01 20-48-57](https://github.com/user-attachments/assets/ea27998d-78d4-4155-b5c3-0ce6cb5a2d4b)
![AnomalyDX11AVX 2024-10-01 20-48-59](https://github.com/user-attachments/assets/43383437-a711-48d2-9e50-97b37fd498d2)
![AnomalyDX11AVX 2024-10-01 20-49-00](https://github.com/user-attachments/assets/8bfb602b-3afd-409a-941e-ca2baa4853d7)
![AnomalyDX11AVX 2024-10-01 20-49-01](https://github.com/user-attachments/assets/8f7e76da-6d33-4b5b-9760-e6d748692361)

**Comment by andtheherois** [comment]
elcan is a 1x or 4x scope. zoom in or out fully
