### ISSUE TITLE
CTD with latest GAMMA update

### ISSUE THREAD

**Issue by Spreadwheat9** [Redotix/GAMMA-3D-Shader-Based-Scopes#26]
Trying to load a save or start a new game with the latest GAMMA and 3DSS update, I get a ctd with the following error:

![image](https://github.com/user-attachments/assets/c6f3d5e6-a78c-4cb9-a92f-013f56bb427e)

For some reason, disabling the mod "300 - Blood pool with trails and steps" solves the issue (worked for me)

**Comment by andtheherois** [comment]
no idea why this works. blood pools is being disabled in the next gamma update for causing busy hands anyway.
