### ISSUE TITLE
PP19 - Vityaz + ACOG 2.8x no 3D shaders

### ISSUE THREAD

**Issue by Spreadwheat9** [Redotix/GAMMA-3D-Shader-Based-Scopes#27]
No 3D shaders effect for the combination below.

PP19 - Vityaz (wpn_vityaz)
ACOG 2.8x (acog)

Base GAMMA weapon drop (the gun dropped with the scoped already attached).
I have no additional weapons mods installed.

![AnomalyDX11AVX 2024-10-20 21-00-45](https://github.com/user-attachments/assets/20f28abd-e747-4848-80e9-cf3a2411fe81)

**Comment by andtheherois** [comment]
cant replicate this. the gun works fine for me. try removing the scope from the gun and attaching it again.
