### ISSUE TITLE
3DSS.Phant0m.s.AKs - e0t2_magd = black sqaure in scope

### ISSUE THREAD

**Issue by Hoshizoku** [Redotix/GAMMA-3D-Shader-Based-Scopes#7]
All of phantoms  _isg AKs have black square in scope with e0t2_magd

packs involved:
[weapons] Phant0m's Endgame BaS AKs - ATHI Edit
3DSS.Phant0m.s.AKs-1.0

https://discord.com/channels/912320241713958912/1219433143069708299/1257580696180883476

**Comment by andtheherois** [comment]
fixed
