### ISSUE TITLE
RD-47 ISG Tactical, wpn_akm_isg, reload anims with no scope attached

### ISSUE THREAD

**Issue by Hoshizoku** [Redotix/GAMMA-3D-Shader-Based-Scopes#8]
Using wpn_akm_isg without a scope attached leads to kaputt reload animation

packs involved: 
[weapons] Phant0m's Endgame BaS AKs - ATHI Edit
3DSS.Phant0m.s.AKs-1.0

https://discord.com/channels/912320241713958912/1219433143069708299/1257578622810722365

**Comment by Hoshizoku** [comment]
Further Comments of user with error:
re: wpn_akm_isg borked model issue, the packs involved are 3DSS for GAMMA (ie the main module) and not 3DSS Phant0m's AKs, since 3DSS for GAMMA has meshes (no sights, and all sights that aren't scopes) that is overwriting the RD-47 ISG from Phant0m's AKs.

**Comment by andtheherois** [comment]
this wasnt an issue. user didnt know what packs they had.
