### ISSUE TITLE
sig sg 550 - sig550_custom, acog, no grass/decal/lighting rendering in scope

### ISSUE THREAD

**Issue by Hoshizoku** [Redotix/GAMMA-3D-Shader-Based-Scopes#9]
sig550_custom, acog
Seems like the acog didnt make it into the new shader era 😢 
(other scopes seem to work)

packs involved:
3DSS.for.GAMMA-1.3

https://discord.com/channels/912320241713958912/1219433143069708299/1257626170384711680

![ss_hoshizoku_07-02-24_11-26-54_(l01_escape)](https://github.com/Redotix/GAMMA-3D-Shader-Based-Scopes/assets/174358400/21ee72bd-ebd6-49b9-a3c5-8d5fdeb9452e)

**Comment by andtheherois** [comment]
fixed
